//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	
	public enum DirectionEnum { Left = 3, Right = 1, Up = 0, Down = 2 };
	public enum ColorEnum { Blue,Orange,Red};
	public enum BallSizeEnum { Normal = 0, Small = 1, Large = 2 };		
}

